"""Add: documents table

Revision ID: 31b0afc294f0
Revises: e4ae7e8e3247
Create Date: 2026-02-24 13:14:26.249110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b0afc294f0'
down_revision: Union[str, Sequence[str], None] = 'e4ae7e8e3247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending_upload', 'uploaded', 'processing', 'ready', 'failed', name='document_status', native_enum=False), server_default='pending_upload', nullable=False),
    sa.Column('purpose', sa.Enum('resume', 'invoice', 'context', name='document_purpose', native_enum=False), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint('size_bytes >= 0', name='ck_documents_size_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum_sha256'),
    sa.UniqueConstraint('storage_key')
    )
    op.add_column('messages', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'type')
    op.drop_table('documents')
    # ### end Alembic commands ###
